import streamlit as st

from game import Game
from case import CHARACTERS, QUESTIONS, ROOMS, MAX_ACTIONS


# ============================================================
# PAGE CONFIG
# ============================================================

st.set_page_config(
    page_title="WHO IS THE MOLE?",
    page_icon="🕵️",
    layout="wide",
    initial_sidebar_state="expanded",
)


# ============================================================
# CSS
# ============================================================

st.markdown(
    """
    <style>
        .stApp {
            background: #0b0d10;
            color: #e8e8e8;
        }

        section[data-testid="stSidebar"] {
            background: #11151a;
            border-right: 1px solid #252a31;
        }

        .title {
            font-size: 4rem;
            font-weight: 900;
            letter-spacing: 0.08em;
            line-height: 1;
            margin-bottom: 0.2rem;
        }

        .subtitle {
            color: #8d96a3;
            font-size: 1.1rem;
            margin-bottom: 2rem;
        }

        .case-box {
            background: #13171c;
            border: 1px solid #292f37;
            border-radius: 12px;
            padding: 22px;
            margin-bottom: 18px;
        }

        .clue-box {
            background: #151a20;
            border-left: 4px solid #d6a84f;
            border-radius: 8px;
            padding: 18px;
            margin: 12px 0;
        }

        .warning-box {
            background: #21191a;
            border-left: 4px solid #c95757;
            border-radius: 8px;
            padding: 16px;
            margin: 12px 0;
        }

        .success-box {
            background: #142019;
            border-left: 4px solid #56a56a;
            border-radius: 8px;
            padding: 16px;
            margin: 12px 0;
        }

        .small-label {
            color: #7d8794;
            text-transform: uppercase;
            letter-spacing: 0.08em;
            font-size: 0.72rem;
            font-weight: 700;
        }

        .room-title {
            font-size: 1.7rem;
            font-weight: 800;
        }

        .evidence-title {
            font-size: 1.15rem;
            font-weight: 800;
            margin-bottom: 8px;
        }

        .quote {
            color: #c8cdd4;
            font-style: italic;
            padding: 10px 14px;
            border-left: 2px solid #555d67;
            margin: 8px 0;
        }

        .character-card {
            background: #13171c;
            border: 1px solid #292f37;
            border-radius: 10px;
            padding: 16px;
            min-height: 130px;
        }

        div.stButton > button {
            border-radius: 8px;
            font-weight: 700;
        }
    </style>
    """,
    unsafe_allow_html=True,
)


# ============================================================
# SESSION STATE
# ============================================================

if "game" not in st.session_state:
    st.session_state.game = Game()

if "started" not in st.session_state:
    st.session_state.started = False

game = st.session_state.game


# ============================================================
# HELPERS
# ============================================================

def reset_game():
    st.session_state.game = Game()
    st.session_state.started = True
    st.rerun()


def get_clue_data(clue):
    """
    Handles both normal clues and partial clues generated by game.py.
    """
    if not isinstance(clue, dict):
        return {}

    data = clue.get("data", clue)

    if not isinstance(data, dict):
        return {}

    return data


def render_clue(clue):
    """
    Render a clue in a human-readable way.
    """

    data = get_clue_data(clue)

    clue_type = data.get("type", clue.get("type", ""))

    # --------------------------------------------------------
    # Laboratory
    # --------------------------------------------------------

    if clue_type in ("lab_report", "lab_note"):
        st.markdown(
            f"""
            <div class="clue-box">
                <div class="small-label">Laboratory Evidence</div>
                <div class="evidence-title">
                    {data.get("title", "INCIDENT REPORT")}
                </div>
            """,
            unsafe_allow_html=True,
        )

        date = data.get("date")
        if date:
            st.markdown(f"**Date:** {date}")

        events = data.get("events", data.get("lines", []))

        if events:
            st.markdown("### Incident Timeline")

            for event in events:
                if isinstance(event, (tuple, list)) and len(event) >= 2:
                    time, description = event[0], event[1]
                    st.markdown(f"**{time}** — {description}")
                else:
                    st.markdown(f"• {event}")

        maintenance = data.get("maintenance", data.get("maintenance_note"))

        if maintenance:
            st.markdown("### Maintenance Note")
            st.markdown(
                f'<div class="quote">{maintenance}</div>',
                unsafe_allow_html=True,
            )

        note = data.get("note")
        if note:
            st.markdown(f"**Investigator note:** {note}")

        signature = data.get("signature")
        if signature:
            st.markdown(f"*{signature}*")

        st.markdown("</div>", unsafe_allow_html=True)

    # --------------------------------------------------------
    # Storage
    # --------------------------------------------------------

    elif clue_type == "storage_log":
        st.markdown(
            f"""
            <div class="clue-box">
                <div class="small-label">Storage Evidence</div>
                <div class="evidence-title">
                    {data.get("title", "RESTRICTED STORAGE ACCESS LOG")}
                </div>
            """,
            unsafe_allow_html=True,
        )

        entries = data.get("entries", [])

        if entries:
            for entry in entries:
                st.markdown(f"• **{entry}**")

        note = data.get("note")
        if note:
            st.markdown(f"**Note:** {note}")

        secondary = data.get("secondary_note")
        if secondary:
            st.markdown(
                f'<div class="quote">{secondary}</div>',
                unsafe_allow_html=True,
            )

        st.markdown("</div>", unsafe_allow_html=True)

    # --------------------------------------------------------
    # Cafeteria
    # --------------------------------------------------------

    elif clue_type in ("cafeteria_log", "vending"):
        st.markdown(
            f"""
            <div class="clue-box">
                <div class="small-label">Cafeteria Evidence</div>
                <div class="evidence-title">
                    {data.get("title", "CAFETERIA SECURITY LOG")}
                </div>
            """,
            unsafe_allow_html=True,
        )

        instruction = data.get("instruction")
        if instruction:
            st.markdown(f"**System instruction:** {instruction}")

        survivors = data.get("survivors")
        if survivors is not None:
            st.markdown(f"**Registered survivors:** {survivors}")

        terminal_id = data.get("terminal_id")
        if terminal_id:
            st.markdown(f"**Terminal ID:** `{terminal_id}`")

        system_log = data.get("system_log")
        if system_log:
            st.markdown("### System Log")
            st.code(system_log)

        note = data.get("note")
        if note:
            st.markdown(f"**Note:** {note}")

        st.markdown("</div>", unsafe_allow_html=True)

    # --------------------------------------------------------
    # Partial clue
    # --------------------------------------------------------

    elif clue_type == "partial":
        st.markdown(
            """
            <div class="clue-box">
                <div class="small-label">Partial Evidence</div>
            """,
            unsafe_allow_html=True,
        )

        message = (
            data.get("message")
            or data.get("note")
            or clue.get("message")
            or "Something about this location has been disturbed."
        )

        st.markdown(message)

        st.markdown("</div>", unsafe_allow_html=True)

    # --------------------------------------------------------
    # Fallback
    # --------------------------------------------------------

    else:
        st.markdown(
            """
            <div class="clue-box">
                <div class="small-label">Evidence</div>
            """,
            unsafe_allow_html=True,
        )

        for key, value in data.items():
            if key == "type":
                continue

            if isinstance(value, list):
                st.markdown(f"**{key.replace('_', ' ').title()}**")
                for item in value:
                    st.markdown(f"• {item}")
            else:
                st.markdown(
                    f"**{key.replace('_', ' ').title()}:** {value}"
                )

        st.markdown("</div>", unsafe_allow_html=True)


def render_response(character, question, response):
    st.markdown(
        f"""
        <div class="case-box">
            <div class="small-label">{character}</div>
            <div class="evidence-title">{question}</div>
            <div class="quote">"{response}"</div>
        </div>
        """,
        unsafe_allow_html=True,
    )


# ============================================================
# START SCREEN
# ============================================================

if not st.session_state.started:

    st.markdown(
        '<div class="title">WHO IS THE MOLE?</div>',
        unsafe_allow_html=True,
    )

    st.markdown(
        '<div class="subtitle">A closed-room investigation in 12 moves.</div>',
        unsafe_allow_html=True,
    )

    st.markdown(
        """
        <div class="case-box">
            <div class="small-label">CASE FILE #047</div>

            <h2>Someone inside the team sabotaged the facility.</h2>

            <p>
            At 23:40, the facility suffered a power fluctuation.
            Three minutes later, the security alarm activated.
            </p>

            <p>
            By 23:50, restricted storage had been accessed,
            emergency systems had been used, and the cafeteria
            security cameras were offline.
            </p>

            <p>
            Five people were inside.
            One of them is lying.
            </p>

            <p>
            Your job is not to find a confession.
            Your job is to find the contradictions.
            </p>
        </div>
        """,
        unsafe_allow_html=True,
    )

    if st.button("🔎 START INVESTIGATION", use_container_width=True):
        st.session_state.started = True
        st.session_state.game = Game()
        st.rerun()

    st.stop()


# ============================================================
# SIDEBAR
# ============================================================

with st.sidebar:

    st.markdown("## 🕵️ INVESTIGATION")

    actions = game.actions_left

    st.metric(
        "Actions Remaining",
        actions,
        delta=f"/ {MAX_ACTIONS}",
    )

    st.progress(max(0, actions) / MAX_ACTIONS)

    st.divider()

    st.markdown("### Investigation Status")

    investigated = getattr(game, "investigated_rooms", set())
    questioned = getattr(game, "questioned_characters", set())

    st.write(
        f"🧪 Rooms searched: **{len(investigated)} / {len(ROOMS)}**"
    )

    st.write(
        f"🗣️ People questioned: **{len(questioned)} / {len(CHARACTERS)}**"
    )

    st.divider()

    st.markdown("### Your Leads")

    if investigated:
        for room in investigated:
            st.write(f"✓ {room}")
    else:
        st.caption("No locations searched yet.")

    if questioned:
        st.markdown("**Questioned:**")
        for character in questioned:
            st.write(f"✓ {character}")

    st.divider()

    if st.button("🔄 Restart Case", use_container_width=True):
        reset_game()


# ============================================================
# HEADER
# ============================================================

st.markdown(
    '<div class="title">WHO IS THE MOLE?</div>',
    unsafe_allow_html=True,
)

st.markdown(
    '<div class="subtitle">Follow the evidence. Trust nobody.</div>',
    unsafe_allow_html=True,
)


# ============================================================
# GAME OVER
# ============================================================

if game.game_over:

    st.markdown("---")

    if getattr(game, "last_accusation_correct", False):
        st.markdown(
            """
            <div class="success-box">
                <h2>CASE SOLVED</h2>
                <p>
                Your accusation was correct.
                The sabotage trail finally came together.
                </p>
            </div>
            """,
            unsafe_allow_html=True,
        )
    else:
        st.markdown(
            """
            <div class="warning-box">
                <h2>WRONG ACCUSATION</h2>
                <p>
                The real culprit escaped your accusation.
                Review the evidence and try the case again.
                </p>
            </div>
            """,
            unsafe_allow_html=True,
        )

    st.markdown("## Evidence Collected")

    clues = game.get_clues()

    if clues:
        for clue in clues:
            render_clue(clue)
    else:
        st.info("You collected no physical evidence.")

    st.divider()

    if st.button("🔁 Play Again", use_container_width=True):
        reset_game()

    st.stop()


# ============================================================
# MAIN TABS
# ============================================================

tab_rooms, tab_questions, tab_evidence, tab_accuse = st.tabs(
    [
        "🧪 INVESTIGATE",
        "🗣️ QUESTION",
        "📁 EVIDENCE",
        "⚖️ ACCUSE",
    ]
)


# ============================================================
# ROOMS TAB
# ============================================================

with tab_rooms:

    st.header("Investigate Locations")

    st.caption(
        "Searching a location costs one action. "
        "Some evidence only becomes useful when combined with other evidence."
    )

    room_columns = st.columns(len(ROOMS))

    for column, (room_name, room_data) in zip(room_columns, ROOMS.items()):

        with column:

            st.markdown(
                f"""
                <div class="character-card">
                    <div style="font-size:2rem;">
                        {room_data.get("icon", "📍")}
                    </div>

                    <div class="room-title">
                        {room_name}
                    </div>

                    <p>
                        {room_data.get("description", "")}
                    </p>
                </div>
                """,
                unsafe_allow_html=True,
            )

            st.write("")

            already = room_name in investigated

            if already:
                st.success("✓ Investigated")

            if st.button(
                f"Search {room_name}",
                key=f"room_{room_name}",
                disabled=already or actions <= 0,
                use_container_width=True,
            ):

                result = game.investigate_room(room_name)

                if result:
                    st.session_state.last_room_result = result

                st.rerun()


    if "last_room_result" in st.session_state:

        st.divider()

        st.subheader("Latest Finding")

        result = st.session_state.last_room_result

        if isinstance(result, dict):
            render_clue(result)
        else:
            st.info(str(result))


# ============================================================
# QUESTIONS TAB
# ============================================================

with tab_questions:

    st.header("Question The Suspects")

    st.caption(
        "Each person can only be questioned once. "
        "Ask questions that help you test the physical evidence."
    )

    for character in CHARACTERS:

        already_questioned = character in questioned

        with st.expander(
            f"{'✓ ' if already_questioned else ''}{character}",
            expanded=False,
        ):

            if already_questioned:
                st.info("You already questioned this person.")
                continue

            selected_question = st.selectbox(
                "Question",
                QUESTIONS,
                key=f"question_{character}",
            )

            if st.button(
                f"Question {character}",
                key=f"ask_{character}",
                disabled=actions <= 0,
                use_container_width=True,
            ):

                response = game.question_character(
                    character,
                    selected_question,
                )

                st.session_state.last_response = (
                    character,
                    selected_question,
                    response,
                )

                st.rerun()


    if "last_response" in st.session_state:

        st.divider()

        st.subheader("Latest Interview")

        character, question, response = st.session_state.last_response

        render_response(
            character,
            question,
            response,
        )


# ============================================================
# EVIDENCE TAB
# ============================================================

with tab_evidence:

    st.header("Evidence Board")

    clues = game.get_clues()

    if not clues:

        st.info(
            "Your evidence board is empty. "
            "Search the Laboratory, Storage, or Cafeteria."
        )

    else:

        st.caption(
            f"{len(clues)} piece(s) of evidence collected."
        )

        for index, clue in enumerate(clues, start=1):

            st.markdown(f"### Evidence #{index}")

            render_clue(clue)

    st.divider()

    st.markdown("### How To Think About The Case")

    st.markdown(
        """
        Don't ask:

        > "Who looks suspicious?"

        Ask:

        - **What happened first?**
        - **Which access record appears twice?**
        - **Who had a reason to know how those systems worked?**
        - **Does someone's story conflict with the physical evidence?**
        - **Can two apparently unrelated clues point to the same person?**

        The game is designed so that no single clue should completely solve
        the case for you.
        """
    )


# ============================================================
# ACCUSATION TAB
# ============================================================

with tab_accuse:

    st.header("Make Your Accusation")

    st.warning(
        "This is your final decision. "
        "Accusing does not consume an investigation action."
    )

    st.markdown(
        """
        <div class="case-box">
            <h3>Before accusing, check your chain of reasoning.</h3>

            <p>
            A strong accusation should connect:
            </p>

            <ol>
                <li>A physical event</li>
                <li>An access record or system trace</li>
                <li>A person's testimony or role</li>
            </ol>

            <p>
            One suspicious statement is not enough.
            Look for corroboration.
            </p>
        </div>
        """,
        unsafe_allow_html=True,
    )

    accusation = st.selectbox(
        "Who is the Mole?",
        ["Select a suspect..."] + CHARACTERS,
    )

    st.write("")

    if st.button(
        "⚖️ MAKE ACCUSATION",
        disabled=accusation == "Select a suspect...",
        use_container_width=True,
    ):

        # IMPORTANT:
        # Game.accuse() should NOT require actions_left > 0.
        correct = game.accuse(accusation)

        # Store this explicitly so the UI doesn't have to know MOLE.
        game.last_accusation_correct = correct

        st.rerun()


# ============================================================
# FOOTER
# ============================================================

st.markdown("---")

st.caption(
    "CASE FILE #047 • Trust the evidence, not the story."
)
